---
title: "Primer reporte en R Markdown"
author: "Gerardo Luna Lopez 135562" 
output: html_document
---

### Introduccion al formato R Markdown  

Ejemplo elaborado en `r date()` .

```{r Paquetes}
library(ggmap)
```

```{r GenerarDatos, message=FALSE}
clave.unica <- rep("135562",3)
es.mixto <- c(universidad = 1, preparatoria = 0, secundaria = 1)

universidad <- geocode("ITAM")
preparatoria <- geocode("Tecoyotitla 366, Ex Hacienda Guadalupe Chimalistac")
secundaria <- geocode("Algodonales 56, Rinconada Coapa")

educacion <- rbind(universidad, preparatoria, secundaria)
educacion <- cbind(clave.unica, es.mixto, educacion)
```

```{r ObtenciónCoordenadasMapas, warning=FALSE,message=FALSE}
limites <- make_bbox(lon, lat, educacion, f = 0.7)
mapa <- get_map(location = limites,
                maptype = "roadmap",
                source = "google")
```

```{r GraficarLocalizaciones, echo=FALSE}
ggmap(mapa) +
geom_point(data = educacion, 
           aes(x = lon, y = lat),
           size = 4, alpha = 0.6, colour = "red")